"""Tests for the normalized alert event model (Phase 1, Task 5.1 acceptance)."""

import json

import pytest
from pydantic import ValidationError

from lib.events import AlertEvent, derive_correlation_key

# A realistic instance of the Section-3 normalized event (concrete values).
SAMPLE = {
    "event_id": "1d4e8c2a-9b3f-4a1e-8c7d-2f6b0a9e1c34",
    "source": "elastic",
    "received_at": "2026-01-01T02:47:00Z",
    "service": "payment-service",
    "environment": "production",
    "severity_hint": "P1",
    "error_code": "ERR_DB_CONN_TIMEOUT",
    "http_status": 503,
    "deployment_id": "deploy-2026-01-01-0000",
    "correlation_key": derive_correlation_key("payment-service", "production", "payments-ns"),
    "message": "Database connection timeout on primary pool",
    "labels": {"k8s_namespace": "payments-ns", "pod": "payment-7c9", "region": "us-central1"},
    "raw": {"original": "untouched source payload"},
}


def test_sample_event_validates_and_round_trips():
    event = AlertEvent.model_validate(SAMPLE)
    assert event.service == "payment-service"
    assert event.source == "elastic"  # use_enum_values -> plain string
    assert event.severity_hint == "P1"
    data = json.loads(event.model_dump_json())
    assert data["correlation_key"] == SAMPLE["correlation_key"]
    assert data["http_status"] == 503


def test_correlation_key_is_deterministic_and_scope_sensitive():
    a = derive_correlation_key("payment-service", "production", "payments-ns")
    b = derive_correlation_key("Payment-Service", " production ", "payments-ns")  # normalized
    c = derive_correlation_key("payment-service", "production", "checkout-ns")
    assert a == b
    assert a != c
    assert len(a) == 32


@pytest.mark.parametrize(
    "bad",
    [
        {**SAMPLE, "source": "nagios"},  # not an allowed source
        {**SAMPLE, "severity_hint": "P9"},  # not an allowed severity
        {**SAMPLE, "http_status": 999},  # invalid HTTP status
        {**SAMPLE, "service": "   "},  # empty after strip
        {**SAMPLE, "unexpected": "nope"},  # extra=forbid
    ],
)
def test_invalid_events_are_rejected(bad):
    with pytest.raises(ValidationError):
        AlertEvent.model_validate(bad)


def test_event_id_autogenerated_when_absent():
    payload = {k: v for k, v in SAMPLE.items() if k != "event_id"}
    event = AlertEvent.model_validate(payload)
    assert event.event_id
